"""crear tabla order

Revision ID: 10c6a4dbe5a4
Revises: 
Create Date: 2023-12-22 01:29:09.854491

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime

# revision identifiers, used by Alembic.
revision = '10c6a4dbe5a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ord_id', sa.String(length=50), nullable=False),
    sa.Column('ord_dt', sa.Date(), nullable=False),
    sa.Column('qt_ordd', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ord_id')
    )
    
    # Obtener la instancia de la tabla
    order_table = sa.Table('order', sa.MetaData(), autoload_with=op.get_bind())

    op.bulk_insert(order_table, [
        {'ord_id': '113-8909896-6940269', 'ord_dt': datetime(2019, 9, 23), 'qt_ordd': 1},
        {'ord_id': '114-0291773-7262677', 'ord_dt': datetime(2020, 1, 1), 'qt_ordd': 1},
        {'ord_id': '114-0291773-7262697', 'ord_dt': datetime(2019, 12, 5), 'qt_ordd': 1},
        {'ord_id': '114-9900513-7761000', 'ord_dt': datetime(2020, 9, 24), 'qt_ordd': 1},
        {'ord_id': '112-5230502-8173028', 'ord_dt': datetime(2020, 1, 30), 'qt_ordd': 1},
        {'ord_id': '112-7714081-3300254', 'ord_dt': datetime(2020, 5, 2), 'qt_ordd': 1},
        {'ord_id': '114-5384551-1465853', 'ord_dt': datetime(2020, 4, 2), 'qt_ordd': 1},
        {'ord_id': '114-7232801-4607440', 'ord_dt': datetime(2020, 10, 9), 'qt_ordd': 1}
    ])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    # ### end Alembic commands ###
